/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jiawei_intelligent_parking_system_view_LinuxActivity */

#ifndef _Included_com_github_jiawei_intelligent_parking_system_view_LinuxActivity
#define _Included_com_github_jiawei_intelligent_parking_system_view_LinuxActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jiawei_intelligent_parking_system_view_LinuxActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jiawei_intelligent_1parking_1system_view_LinuxActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
